require("prototypes.recipes.crafting")
require("prototypes.recipes.metallurgy")
require("prototypes.items.metallurgy")
require("prototypes.entities.blast-furnace")
require("prototypes.entities.forge")
require("prototypes.treefarmconfig")
